In [3]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

target_url="https://raw.githubusercontent.com/ogduartev/energyDataScience/main/data/generation/sample01.csv"
df = pd.read_csv(target_url)

In [4]:
df

           Fecha      FÓSIL  HIDRAÚLICA   BIOMASA    EÓLICA     SOLAR
0     2015-01-01  49.365506   85.413635  0.458204  0.278397       NaN
1     2015-01-02  51.225594  104.981690  0.606667  0.302720       NaN
2     2015-01-03  53.398835  103.865851  0.896885  0.298579       NaN
3     2015-01-04  54.676543   92.117862  1.234003  0.225875       NaN
4     2015-01-05  60.009491  112.142571  1.236390  0.075516       NaN
...          ...        ...         ...       ...       ...       ...
2662  2022-04-16  26.980420  163.362772  2.048671  0.152820  0.809246
2663  2022-04-17  26.225824  156.165404  2.049028  0.094654  1.100669
2664  2022-04-18  27.784780  178.353423  1.769007  0.054251  0.863490
2665  2022-04-19  25.384859  182.876608  1.609322  0.044607  0.838457
2666  2022-04-20  29.607051  177.500853  1.465380  0.002938  1.070572

[2667 rows x 6 columns]