In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

target_url="https://raw.githubusercontent.com/ogduartev/energyDataScience/main/data/stock/sample01.csv"
df = pd.read_csv(target_url)

In [2]:
df

,Fecha,AGUA,CARBON,GAS,LIQUIDOS,PPP Bolsa Mes,Precio Min. Bolsa diario,Precio Max. Bolsa diario,PPP Bolsa diario
0,2015-01-01 00:00:00,187.381526,123.225318,204.977354,971.700598,189.972555,111.699107,212.210107,179.685917
1,2015-01-02 00:00:00,179.863045,119.771853,208.442936,971.705305,189.972555,84.480854,248.480854,187.894382
2,2015-01-03 00:00:00,202.829047,123.878501,213.453856,971.381271,189.972555,153.869354,248.869354,201.160360
3,2015-01-04 00:00:00,230.330204,124.526534,212.540171,947.097082,189.972555,122.913838,242.913838,238.800040
4,2015-01-05 00:00:00,205.850445,125.271973,212.464471,979.080505,189.972555,143.603771,251.603771,214.787935
...,...,...,...,...,...,...,...,...,...
2642,2022-03-27 00:00:00,182.604901,262.813092,697.442903,707.583803,229.404707,247.933748,251.683748,249.882042
2643,2022-03-28 00:00:00,198.853818,262.813092,728.107974,707.583803,229.404707,245.975122,347.975122,274.869332
2644,2022-03-29 00:00:00,202.910992,253.749212,709.119964,707.583803,229.404707,244.046627,349.047627,281.697472
2645,2022-03-30 00:00:00,184.610429,258.967234,718.866090,707.583803,229.404707,234.064132,355.064132,282.618263
2646,2022-03-31 00:00:00,211.776199,264.869713,746.026954,681.372044,229.404707,258.694566,358.695566,312.860782